language: cpp

compiler:
  - gcc
  - clang

env:
  - BTYPE="-DCMAKE_BUILD_TYPE=Debug -DWITH_QGLVIEWER=false  -DWITH_CAIRO=false -DWITH_MAGICK=false -DWITH_GMP=false  -DDGTAL_BUILD_TESTING=OFF" 

script: 
  - cmake . $BTYPE
  - make

